### ISSUE TITLE
kibana can't find mapping 

### ISSUE THREAD

**Issue by BioSt0rm** [TravisFSmith/SweetSecurity#5]
Aftr install and manual start of kibana "sudo sh /opt/kibana/bin/kibana "

Kibana is unable to find the logstash-\* index. 

Error: 
unable to fetch mapping

**Comment by ronaldstoner** [comment]
I have the same issue on the Pi 3/Raspian Jesse. Kibana, elasticsearch, and logstash all fail to start.  Once services are manually restarted everything seems to respond on the correct ports, but logstash does not seem to be creating indexes.

**Comment by guy38370** [comment]
I've same issue on a PI2
Any idea to solve it ?

**Comment by TravisFSmith** [comment]
Can you post any excerpts from the logstash log file to help give an indication as to what may be happening?

**Comment by guy38370** [comment]
In /var/log/logstash there's following files:
0 -rw-r--r-- 1 root root     0 May 13 06:25 logstash.err
88 -rw-r--r-- 1 root root 87349 May 13 06:25 logstash.err.1
 4 -rw-r--r-- 1 root root  2470 May 12 06:25 logstash.err.2.gz
 4 -rw-r--r-- 1 root root  2469 May 10 06:25 logstash.err.3.gz
 0 -rw-r--r-- 1 root root     0 May 12 20:26 logstash.stdout
With in logstash.err.1 following !st lines:
io/console on JRuby shells out to stty for most operations
LoadError: Could not load FFI Provider: (NotImplementedError) FFI not available: java.lang.UnsatisfiedLinkError: /var/lib/logstash/jffi3051690098859420415.so: /var/lib/logstash/jffi3051690098859420415.so: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at com.kenai.jffi.internal.StubLoader.loadFromJar(StubLoader.java:361)
        at com.kenai.jffi.internal.StubLoader.load(StubLoader.java:254)
        at com.kenai.jffi.internal.StubLoader.<clinit>(StubLoader.java:434)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at com.kenai.jffi.Init.load(Init.java:68)
        at com.kenai.jffi.Foreign$InstanceHolder.getInstanceHolder(Foreign.java:49)
        at com.kenai.jffi.Foreign$InstanceHolder.<clinit>(Foreign.java:45)
        at com.kenai.jffi.Foreign.getInstance(Foreign.java:103)
        at com.kenai.jffi.Platform.isSupported(Platform.java:370)
        at org.jruby.ext.ffi.jffi.Factory.<init>(Factory.java:16)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

**Comment by TravisFSmith** [comment]
Looks like an error with the JFFI stuff.  Can you confirm that the new JFFI was installed?  Lines 64-71 of the latest script if you wanted to re-run the installation.

**Comment by guy38370** [comment]
I ran the installation script few days ago
Anyway re-run the jffi installation and now it looks better

Nevertheless Kibana is still unable to fetch maping
Any other verifications to do ?

Note: after each pi reboot i'm obliged to restart services to get Kibana operational

**Comment by guy38370** [comment]
I've below content in logstash.log
Normal ?

pi@PiWall:/var/log/logstash $ cat logstash.log
{:timestamp=>"2016-05-16T10:36:54.660000+0200", :message=>"fetched an invalid config", :config=>"input { \n  #stdin { } \n  file {\n    path => \"/opt/nsm/bro/logs/current/_.log\"   \n    sincedb_path => \"/opt/nsm/bro/logs/current/_.log\"\n    start_position => \"beginning\" \n  }\n}\n\nfilter {\n  if [message] =~ /^(\d+\.\d{6}\s+\S+\s+(?:[\d\.]+|[\w:]+|-)\s+(?:\d+|-)\s+(?:[\d\.]+|[\w:]+|-)\s+(?:\d+|-)\s+\S+\s+\S+\s+\S+\s+\S+\s+[^:]+::\S+\s+[^:]+::\S+\s+\S+(?:\s\S+)*$)/ {\n    grok{\n      patterns_dir => \"/etc/logstash/custom_patterns\"\n      match => {\n        message => \"%{291009}\"\n      }\n      add_field => [ \"rule_id\", \"291009\" ]\n      add_field => [ \"Device Type\", \"IPSIDSDevice\" ]\n      add_field => [ \"Object\", \"Process\" ]\n      add_field => [ \"Action\", \"General\" ]\n      add_field => [ \"Status\", \"Informational\" ]\n    }\n  }\n  translate { \n    field => \"evt_dstip\"\n    destination => \"tor_IP\"\n    dictionary_path => '/etc/logstash/translate/torIP.yaml'\n  }\n  translate { \n    field => \"evt_srcip\"\n    destination => \"tor_IP\"\n    dictionary_path => '/etc/logstash/translate/torIP.yaml'\n  }  \n  translate { \n    field => \"evt_dstip\"\n    destination => \"malicious_IP\"\n    dictionary_path => '/etc/logstash/translate/maliciousIP.yaml'\n  }\n  translate { \n    field => \"evt_srcip\"\n    destination => \"malicious_IP\"\n    dictionary_path => '/etc/logstash/translate/maliciousIP.yaml'\n  }  \n  date {\n    match => [ \"start_time\", \"UNIX\" ]\n  }\n}\n\noutput { \n  stdout { \n    codec => rubydebug \n  }\n  if [tor_IP] == \"YES\" {\n   email  {\n        address => \"smtp.gmail.com\",\n        from => \"guy.38.bellon@gmail.com\"\n        htmlbody => \"Traffic has been detected coming from or going to a TOR Exit Node IP address.  <br/><br/>\n<b>Source IP: </b>%{evt_srcip}<br/>\n<b>Source Port: </b>%{evt_srcport}<br/>\n<b>Destination IP: </b>%{evt_dstip}<br/>\n<b>Destination Port: </b>%{evt_dstport}<br/><br/>\n<b>Raw Log: </b>%{message}\"\n        password => \"XXXXXXX\"\n        port => 587\n        subject => \"Tor Exit IP Detected by SweetSecurity\"\n        to => \"guy.38.bellon@gmail.com\"\n        use_tls => true\n        username => \"guy.38.bellon@gmail.com\"\n     }\n  }\n  \n  if [malicious_IP] == \"YES\" {\n   email  {\n        address => \"smtp.gmail.com\",\n        from => \"guy.38.bellon@gmail.com\"\n        htmlbody => \"Traffic has been detected coming from or going to a malicious IP address.  <br/><br/>\n<b>Source IP: </b>%{evt_srcip}<br/>\n<b>Source Port: </b>%{evt_srcport}<br/>\n<b>Destination IP: </b>%{evt_dstip}<br/>\n<b>Destination Port: </b>%{evt_dstport}<br/><br/>\n<b>Raw Log: </b>%{message}\"\n        password => \"XXXXXXXXXXX\"\n        port => 587\n        subject => \"Malicious IP Detected by SweetSecurity\"\n        to => \"guy.38.bellon@gmail.com\"\n        use_tls => true\n        username => \"guy.38.bellon@gmail.com\"\n     }\n  }\n\n  elasticsearch { \n    hosts => localhost \n  } \n}\n\n", :reason=>"Expected one of #, {, } at line 55, column 36 (byte 1459) after output { \n  stdout { \n    codec => rubydebug \n  }\n  if [tor_IP] == \"YES\" {\n   email  {\n        address => \"smtp.gmail.com\"", :level=>:error}

**Comment by guy38370** [comment]
below files in bro log directory
No ".log" file . => error ?

pi@PiWall:/opt/nsm/bro/logs/current $ ls -lsa
total 112
4 drwxr-xr-x 3 root root 4096 May 11 20:42 .
4 drwxr-xr-x 5 root root 4096 May  9 20:53 ..
4 -rw-r--r-- 1 root root  121 May  9 20:52 .cmdline
4 -rw-r--r-- 1 root root  496 May 11 20:42 communication.log
4 -rw-r--r-- 1 root root 2302 May 11 20:42 conn.log
4 -rw-r--r-- 1 root root  331 May  9 20:52 .env_vars
4 -rw-r--r-- 1 root root  772 May 11 20:42 notice.log
4 -rw-r--r-- 1 root root    6 May  9 20:52 .pid
4 -rw-r--r-- 1 root root   18 May  9 21:00 .rotated.communication
4 -rw-r--r-- 1 root root   18 May 11 20:42 .rotated.conn
4 -rw-r--r-- 1 root root   18 May 11 20:42 .rotated.conn-summary
4 -rw-r--r-- 1 root root   18 May 11 17:00 .rotated.dhcp
4 -rw-r--r-- 1 root root   18 May 11 20:42 .rotated.dns
4 -rw-r--r-- 1 root root   18 May 11 18:00 .rotated.dpd
4 -rw-r--r-- 1 root root   18 May  9 22:00 .rotated.files
4 -rw-r--r-- 1 root root   18 May 10 20:00 .rotated.http
4 -rw-r--r-- 1 root root   18 May 10 23:00 .rotated.known_services
4 -rw-r--r-- 1 root root   18 May  9 21:00 .rotated.loaded_scripts
4 -rw-r--r-- 1 root root   18 May 11 11:00 .rotated.notice
4 -rw-r--r-- 1 root root   18 May  9 21:00 .rotated.packet_filter
4 -rw-r--r-- 1 root root   18 May 11 20:42 .rotated.reporter
4 -rw-r--r-- 1 root root   18 May 10 21:00 .rotated.software
4 -rw-r--r-- 1 root root   18 May 11 20:42 .rotated.weird
4 -rw-r--r-- 1 root root   59 May  9 20:52 .startup
4 drwx------ 3 root root 4096 May 11 20:42 .state
4 -rwx------ 1 root root   20 May 11 20:42 .status
4 -rw-r--r-- 1 root root 2084 May 11 20:42 stderr.log
4 -rw-r--r-- 1 root root  188 May  9 20:52 stdout.log
pi@PiWall:/opt/nsm/bro/logs/current $

**Comment by crypiehef** [comment]
I'm having the same problem with Kibana no being able to fetch the logstash-\* index.

**Comment by TravisFSmith** [comment]
Try manually running logstash to see if there are any issues with the configuration.  The command for that is /opt/logstash/bin/logstash -f /etc/logstash/conf.d/logstash.conf

This should at least output from information about what may be the problem, such as not finding a yaml file or other supporting config files. Paste results here and we can figure out what the issue may be.

**Comment by webhead404** [comment]
Here is my full output:

io/console not supported; tty will not be manipulated
Settings: Default pipeline workers: 4
Invalid setting for email output plugin:

  output {
    email {
      # This setting must be a number
      # Expected number, got "SMTP_PORT" (type SMTP_PORT)
      port => "SMTP_PORT"
      ...
    }
  } {:level=>:error}
Pipeline aborted due to error {:exception=>#<LogStash::ConfigurationError: Something is wrong with your configuration.>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/config/mixin.rb:134:in `config_init'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/outputs/base.rb:63:in`initialize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/output_delegator.rb:74:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:181:in`start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:181:in`start_workers'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:136:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/agent.rb:465:in`start_pipeline'"], :level=>:error}
stopping pipeline {:id=>"main"}

I don't understand why I'm getting this because I filled out the relevant information at the start of the script. Also I need some guidance as to why this would affect indices in Kibana.

**Comment by TravisFSmith** [comment]
Without knowing what you entered when prompted for the initializing script, it's hard to say why it didn't format the config file correctly.  For now, you can remove the email {...} section under output.  Alternatively you can manually input the email settings in the config file.  

The reason why it effects the indices is that logstash is failing to start to be able to normalize any data.  Since it hasn't normalized any data, Kibana does not have any indices to load.

**Comment by webhead404** [comment]
For the time being I went ahead and filled in my data in the config file. Now my output says that the pipeline main has started. I still have the same issue.

**Comment by webhead404** [comment]
Here is my newest log.

{:timestamp=>"2016-07-28T00:33:53.643000+0000", :message=>"Pipeline aborted due to error", :exception=>#<LogStash::ConfigurationError: Something is wrong with your configuration.>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/config/mixin.rb:134:in `config_init'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/outputs/base.rb:63:in`initialize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/output_delegator.rb:74:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:181:in`start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:181:in`start_workers'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:136:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/agent.rb:465:in`start_pipeline'"], :level=>:error}
{:timestamp=>"2016-07-28T00:33:56.659000+0000", :message=>"stopping pipeline", :id=>"main"}
{:timestamp=>"2016-07-28T03:34:26.854000+0000", :message=>"Pipeline main started"}
{:timestamp=>"2016-07-28T21:47:42.019000+0000", :message=>"Connection refused", :class=>"Manticore::SocketException", :level=>:error}
{:timestamp=>"2016-07-28T21:47:44.115000+0000", :message=>"Pipeline main started"}

**Comment by TravisFSmith** [comment]
The logs are saying that the connection is refused, which most likely is a connection to elastic search.  Run the command to check if elasticsearch is running or not.  If it is not running, you can start the service and try the command again.  Once it's running, the connection refused error should go away. 

curl 'localhost:9200/_cat/health?v'

**Comment by webhead404** [comment]
It says that elasticsearch's status is yellow. active shards 50%.

**Comment by TravisFSmith** [comment]
Should be OK then.  Copy this to a sample config file and see if logstash can write to your elasticsearch instance.  Command will be /opt/logstash/bin/logstash -f <file_name.conf>

You should be able to just type jibberish into the console (stdin) and see it write to elasticsearch and the console (stdout).  If it's successful, kibana should see the index created. 

```
input { 
  stdin { } 
}
output {
  stdout { 
    codec => rubydebug 
  }
  elasticsearch { 
    hosts => localhost 
  } 
}
```

**Comment by webhead404** [comment]
Kibana was able to see the timestamp index with this one.After reuploading my original configuration and playing around with it the log file still tries to reference (SMTP_PORT) (I have verified it is 587 in my config) I'm at a loss at this point.

**Comment by n00btotal** [comment]
I'm also trying to figure this out. I have very little experience of Bro, kibana etc. But "out of the box" (after following your sweetsecurity setup script) Kibana is not presenting any information.

I've followed the advice given above. I get no errors from the different components.

Do I have to manually enter any index patterns or should they show up automatically? 

![kibana-screenshot](https://cloud.githubusercontent.com/assets/83351/17438331/97f4d402-5b22-11e6-80a7-118321a4c375.png)

**Comment by guy38370** [comment]
I finally solve all issue to have system running:
1st Jffi stuff don't compile successfully when lunch inside script Sweetsecurity.... out of memory ..... So do it manually
2nd sed function do not work properly so i edit concerned configuration files to put manually Email address and other parameters
3rd After reboot finished i've to restart manually services (last lines of script). I've haven't found yet how to solve it but it's minor problem
Next it's running well and you can make your settings in kibane

The main problem i'm facing now is that when i make my switch port mirrorring for monitoring traffic the raspberry goes overloaded ...  ==> Any idea to solve it ? Cluster ?

**Comment by n00btotal** [comment]
I re-ran parts of the install script, even though I could not find any errors in the individual components. 

The following part went smoother the second time. No idea why though.. And the first time it just took really long time.

`sudo dpkg -i node_latest_armhf.deb`

I do not know if it mattered, but I also corrected the indentation the logstash.conf file.

Anyway, it is working for me now. Sorry I couldn't be more accurate about what was the cause.

**Comment by shyheim1** [comment]
I'm experiencing the same issue with timestamp index as the others have described. I've tried all the above steps and still cannot get it working. Can anyone provide any more specific detail or steps to get index fetching working?

**Comment by cb259** [comment]
ElasticSearch was running on port 9200 for my install. Modifying the logstash.conf file with the following got me past the "Unable to fetch mapping" error in Kibanna.

elasticsearch {
    hosts => localhost:9200
  }

Note: This should be under the output section

**Comment by TravisFSmith** [comment]
Appears all the issues in here have been resolved.  v2.0 has included everything noted.
